experiment: ht
use_key: false
model:
  input_size: 88
  d_model: 256
  frames_per_patch: 1
  n_head: 4
  num_encoder_layers: 2
  dim_feedforward: 256
  dropout: 0.2
  n_beats: 32
  beat_resolution: 12
  label_resolution: 12
  boundary_kernel: 5
  window_radius: 2
training:
  device: cuda:1
  seed: 42
  # data_root: event_root/symbol_npz_ht
  # vocab_path: event_root/symbol_w_key_vocab.pkl
  data_root: event_root/pop909_npz_ht
  vocab_path: event_root/pop909_vocab.pkl
  use_augmentation: true
  batch_size: 32
  num_workers: 4
  num_epochs: 100
  learning_rate: 1.0e-4
  min_learning_rate: 1.0e-5
  weight_decay: 1.0e-2
  scheduler:
    warmup_steps: 4000
  save_dir: checkpoints/pop909_ht

